### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by rPromptt** [atishdixit16/feature-selection-using-ant-colony-optimisation-#1]
Hi @atishdixit16, I get the following error message when I run the ACO output:

Error in pherImpProd[, citiesNotCovered] : incorrect number of dimensions.

Please do you have an idea what may be causing this and if possible confirm
reproducibility.

Thanks.

**Comment by Kay9Man** [comment]
library(dplyr)

starwars %%
        filter(homeworld == "Tatooine")%%
        select(name, height, mass, haircolor) -> tatooine

**Comment by Kay9Man** [comment]
``` r
library(dplyr)

starwars %%
        filter(homeworld == "Tatooine")%%
        select(name, height, mass, haircolor) -> tatooine


#> Error in filter(homeworld == "Tatooine"): object 'homeworld' not found
```
